from . import Flask, FbBot


ACCESS_TOKEN = 'EAAKnsCzlM7wBAM0waYVmDwMFMg1s6GMDoDCXSV1ZADQ9xxhzonZAKhHmJ8TZBhN58IKd9cUlAprdc1lBPFhXmRQTmBv8aNZAq6ko2wVTwF0xxOKDkwrD2iRKeQEVzjCk2J6eNAfCzkD2uQ4rGv96QwZC24p8sZC2GrS4uv25WNgQZDZD'
VERIFY_TOKEN = 'VERIFY_TOKEN'
app = Flask(__name__)
fb_bot = FbBot(ACCESS_TOKEN)
